import DashboardLayout from "@/components/DashboardLayout";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { BellRing, CircleDashed, Megaphone, Send } from "lucide-react";
import React, { FormEvent, useState } from "react";
import { toast } from "sonner";

type Visibility = "all" | "unit_only";
type Announcement = { id: number; title: string; body: string; visibility: Visibility; unitId: number | null; publishedAt: Date | null; expiresAt: Date | null };

export function AnnouncementsPage() {
  const utils = trpc.useUtils();
  const { user } = useAuth();
  const permission = trpc.court.registration.myPermission.useQuery();
  const announcements = trpc.court.announcements.list.useQuery();
  const units = trpc.court.units.list.useQuery(undefined, { enabled: permission.data === "full_control" });
  const canPublish = permission.data === "full_control" && user?.role === "admin";
  const [form, setForm] = useState({ title: "", body: "", visibility: "all" as Visibility, unitId: "", expiresAt: "" });
  const [editingId, setEditingId] = useState<number | null>(null);
  const publish = trpc.court.announcements.create.useMutation({ onSuccess: async () => { await utils.court.announcements.list.invalidate(); setForm({ title: "", body: "", visibility: "all", unitId: "", expiresAt: "" }); toast.success("تم نشر الإعلان الداخلي."); } });
  const updateAnnouncement = trpc.court.announcements.update.useMutation({ onSuccess: async () => { await utils.court.announcements.list.invalidate(); setEditingId(null); setForm({ title: "", body: "", visibility: "all", unitId: "", expiresAt: "" }); toast.success("تم تحديث الإعلان."); } });
  const deleteAnnouncement = trpc.court.announcements.delete.useMutation({ onSuccess: async () => { await utils.court.announcements.list.invalidate(); toast.success("تم حذف الإعلان."); } });
  const startEdit = (item: Announcement) => { setEditingId(item.id); setForm({ title: item.title, body: item.body, visibility: item.visibility, unitId: item.unitId ? String(item.unitId) : "", expiresAt: item.expiresAt ? new Date(item.expiresAt).toISOString().slice(0, 16) : "" }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const submit = (event: FormEvent) => { event.preventDefault(); if (!canPublish) return; if (editingId) { updateAnnouncement.mutate({ id: editingId, title: form.title, body: form.body, visibility: form.visibility, unitId: form.visibility === "unit_only" ? Number(form.unitId) : null, expiresAt: form.expiresAt ? new Date(form.expiresAt) : null }); } else { publish.mutate({ title: form.title, body: form.body, visibility: form.visibility, unitId: form.visibility === "unit_only" ? Number(form.unitId) : undefined, expiresAt: form.expiresAt ? new Date(form.expiresAt) : undefined }); } };
  const items = (announcements.data as Announcement[] | undefined) ?? [];

  return <DashboardLayout><section className="mx-auto max-w-6xl"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold tracking-[0.14em] text-[#b18448]">تواصل داخلي منضبط</p><h1 className="mt-2 text-3xl font-bold text-[#12352f]">الإعلانات الداخلية</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-[#65766d]">إعلانات مرئية ضمن نطاق المستخدم أو وحدته، مع حصر النشر بمالك الصلاحية الكاملة وتسجيله في سجل الحركة.</p></div><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#e9f0ea] text-[#1f5a47]"><Megaphone className="h-6 w-6" /></div></div>
    <div className={`mt-7 grid gap-5 ${canPublish ? "xl:grid-cols-[22rem_minmax(0,1fr)]" : ""}`}>{canPublish && <form onSubmit={submit} className="rounded-[1.5rem] border border-[#e7e0d4] bg-white p-5 shadow-[0_10px_30px_rgba(30,51,42,0.05)]"><div className="flex items-center gap-2 text-[#12352f]"><Send className="h-5 w-5 text-[#b18448]" /><h2 className="font-bold">نشر إعلان</h2></div><p className="mt-2 text-xs leading-6 text-[#74817a]">ينشر الإعلان فور الحفظ ولا يظهر خارج نطاقه المحدد.</p><div className="mt-5 space-y-3"><Input value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} placeholder="عنوان الإعلان" required /><textarea value={form.body} onChange={event => setForm({ ...form, body: event.target.value })} placeholder="نص الإعلان" className="min-h-32 w-full rounded-md border border-input bg-transparent p-3 text-sm" required /><select aria-label="نطاق الإعلان" value={form.visibility} onChange={event => setForm({ ...form, visibility: event.target.value as Visibility, unitId: event.target.value === "all" ? "" : form.unitId })} className="h-10 w-full rounded-md border border-input bg-transparent px-3 text-sm"><option value="all">جميع المستخدمين</option><option value="unit_only">وحدة تنظيمية محددة</option></select>{form.visibility === "unit_only" && <select aria-label="الوحدة التنظيمية" value={form.unitId} onChange={event => setForm({ ...form, unitId: event.target.value })} className="h-10 w-full rounded-md border border-input bg-transparent px-3 text-sm" required><option value="">اختر الوحدة</option>{units.data?.map(unit => <option key={unit.id} value={unit.id}>{unit.name}</option>)}</select>}<label className="mt-3 block text-xs font-bold text-[#5a6b62]">تاريخ انتهاء الإعلان (اختياري)<input type="datetime-local" value={form.expiresAt} onChange={event => setForm({ ...form, expiresAt: event.target.value })} className="mt-1 h-10 w-full rounded-md border border-input bg-transparent px-3 text-sm" /></label></div><Button disabled={publish.isPending || (form.visibility === "unit_only" && !form.unitId)} className="mt-5 w-full bg-[#006c35] hover:bg-[#00552b]">{publish.isPending ? "جارٍ النشر…" : "نشر الإعلان"}</Button>{publish.error && <p role="alert" className="mt-3 rounded-xl bg-[#fbe9e4] px-3 py-2 text-xs text-[#9a4634]">{publish.error.message}</p>}</form>}
      <div className="rounded-[1.5rem] border border-[#e7e0d4] bg-white p-5 shadow-[0_10px_30px_rgba(30,51,42,0.05)]"><div className="flex items-center gap-2 text-[#12352f]"><BellRing className="h-5 w-5 text-[#b18448]" /><h2 className="font-bold">الإعلانات الظاهرة لك</h2></div>{announcements.isLoading ? <div className="mt-6 flex items-center gap-2 text-sm text-[#6e7e75]"><CircleDashed className="h-4 w-4 animate-spin" /> جارٍ تحميل الإعلانات…</div> : items.length ? <div className="mt-5 divide-y divide-[#eee8de]">{items.map((item, index) => <article key={item.id} className={`animate-in fade-in slide-in-from-bottom-2 fill-mode-both py-5 duration-300 ${index === 0 ? "rounded-2xl border border-[#cfe0d1] bg-[#f5faf4] px-4 shadow-[0_10px_24px_rgba(30,71,53,0.07)]" : ""}`} style={index === 0 ? { animationDelay: "0ms" } : { animationDelay: `${Math.min(index * 60, 400)}ms` }}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="font-bold text-[#29463b]">{item.title}</h3>{index === 0 && <span className="animate-pulse rounded-full bg-[#e7f2e9] px-2.5 py-0.5 text-[10px] font-black text-[#1f7a4d]">جديد</span>}</div><p className="mt-2 max-w-3xl whitespace-pre-wrap text-sm leading-7 text-[#64746b]">{item.body}</p></div><span className="rounded-full bg-[#edf3eb] px-3 py-1 text-xs font-bold text-[#386048]">{item.visibility === "all" ? "عام" : "ضمن الوحدة"}</span></div><p className="mt-3 text-xs text-[#85938d]">نشر في {item.publishedAt ? new Date(item.publishedAt).toLocaleDateString("ar-SA") : "—"}{item.expiresAt ? ` · ينتهي ${new Date(item.expiresAt).toLocaleDateString("ar-SA")}` : ""}</p>{canPublish && <div className="mt-3 flex gap-2"><button type="button" onClick={() => startEdit(item)} className="rounded-lg border border-[#d8e6dc] px-3 py-1.5 text-xs font-bold text-[#245f43] hover:bg-[#eef5ef]">تعديل</button><button type="button" onClick={() => deleteAnnouncement.mutate({ id: item.id })} className="rounded-lg border border-[#f0d7d0] px-3 py-1.5 text-xs font-bold text-[#a04a35] hover:bg-[#fbeae5]">حذف</button></div>}</article>)}</div> : <div className="mt-5 rounded-2xl border border-dashed border-[#d8d1c5] bg-[#fbfaf6] px-5 py-10 text-center text-sm leading-7 text-[#738179]">لا توجد إعلانات داخلية ظاهرة لك حالياً.</div>}{announcements.error && <p role="alert" className="mt-4 rounded-xl bg-[#fbe9e4] px-3 py-2 text-xs text-[#9a4634]">{announcements.error.message}</p>}</div></div>
  </section></DashboardLayout>;
}
